source_dir = ".test_data"
watch_mode = false

[[rules]]
name = "Images"
extensions = ["jpg", "jpeg", "png", "gif"]
patterns = []
destination = "Images"

[[rules]]
name = "Documents"
extensions = ["pdf", "docx", "txt"]
patterns = []
destination = "Docs"

[[rules]]
name = "Videos"
extensions = ["mp4", "mkv", "mov"]
patterns = []
destination = "Videos"
